In [1]:
import pandas as pd
from myopic_mces import MCES, construct_graph
from myopic_mces.MCES_ILP import get_ilp_itself
from itertools import product
from tqdm.cli import tqdm
from IPython.display import clear_output
from functools import lru_cache
from myopic_mces import construct_graph
import pulp
import networkx as nx

smiles_a, smiles_b = ['CC(=O)OC1=CC=CC=C1C(=O)O'], ['CN1C=NC2=C1C(=O)N(C(=O)N2C)C']
# smiles_a, smiles_b = ['CCc1ccccc1'], ['C=Cc1ccccc1']
G1 = construct_graph(smiles_a[0])
G2 = construct_graph(smiles_b[0])
ilp = get_ilp_itself(G1, G2, -1)

In [2]:
ilp.solve()
ilp.objective.value()

Welcome to the CBC MILP Solver 
Version: 2.10.3 
Build Date: Dec 15 2019 

command line - /home/tornikeo/micromamba/envs/pb/lib/python3.10/site-packages/pulp/solverdir/cbc/linux/64/cbc /tmp/e30bccf7e3a146139ede9d69ac2166d6-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/e30bccf7e3a146139ede9d69ac2166d6-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 437 COLUMNS
At line 1427 RHS
At line 1860 BOUNDS
At line 1995 ENDATA
Problem MODEL has 432 rows, 134 columns and 683 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 27 - 0.00 seconds
Cgl0003I 0 fixed, 0 tightened bounds, 6 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 0 tightened bounds, 6 strengthened rows, 0 substitutions
Cgl0004I processed model has 92 rows, 81 columns (81 integer (81 of which binary)) and 327 elements
Cutoff increment increased from 1e-05 to 0.4999
Cbc0038I Initial state - 0 integers

27.0

In [23]:
from scipy.optimize import milp, LinearConstraint, Bounds
import numpy as np
import pulp

import numpy as np
import pulp

def extract_lp_matrices(model):
    """
    Extracts (c, A, ub, lb) matrices from a PuLP ILP model where all variables are binary.
    """
    # Ensure the problem is a maximization problem

    # Get list of variables in sorted order
    variables = list(model.variables())
    variables.sort(key=lambda v: v.name)
    var_hash = [v.hash for v in variables]
    num_vars = len(variables)

    # Extract objective coefficients (c)
    c = np.array([model.objective.get(v, 0) for v in variables])
    if model.sense == pulp.LpMaximize:
        c = -c

    # Extract constraint matrix (A) and bounds (ub)
    constraint_list = list(model.constraints.values())
    num_constraints = len(constraint_list)

    A = np.zeros((num_constraints, num_vars))
    ub = np.zeros(num_constraints)

    for i, constraint in enumerate(constraint_list):
        ub[i] = -constraint.constant
        for var, coeff in constraint.items():
            j = var_hash.index(var.hash)  # Find index of variable
            A[i, j] = coeff
        # Convert equality constraints to two inequalities if needed
        if constraint.sense == pulp.LpConstraintEQ:
            A = np.vstack([A, -A[i, :]])
            ub = np.hstack([ub, -ub[i]])
    # All variables are binary, so lower and upper bounds are known
    return c, A, ub

# Example usage with a PuLP model
# model = pulp.LpProblem("Example", pulp.LpMaximize)
# x1 = pulp.LpVariable("x1", cat="Binary")
# x2 = pulp.LpVariable("x2", cat="Binary")

# model += 3*x1 + 5*x2  # Objective function
# model += 2*x1 + 3*x2 <= 4  # Constraint 1
# model += x1 + 4*x2 <= 3  # Constraint 2

c, A, ub = extract_lp_matrices(ilp)
print("c:", c)
print("A:", A)
print("ub:", ub)

# c, A, ub, lb = extract_lp_matrices(ilp)
res = milp(
    c=c, 
    constraints=LinearConstraint(
        A=A,
        ub=ub,
    ), 
    integrality=np.ones_like(c), 
    bounds=Bounds(0, 1)
)

res

c: [0.5 0.5 1.  0.  0.  2.  1.  1.  1.  0.  0.  2.  1.  1.  1.  1.  1.  1.
 0.  0.  1.5 0.  0.  1.5 0.  0.  1.5 0.  0.  1.5 0.  0.  1.5 0.  0.  1.5
 0.5 0.5 1.  1.  1.5 1.5 1.  1.5 1.5 1.5 1.5 1.5 2.  1.5 1.  1.5 2.  1.5
 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
 0.  0.  0.  0.  0.  0.  0.  0. ]
A: [[ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 ...
 [-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]]
ub: [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  0.  0.  0.  0.  0.  0.  0.  0.  0

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: 27.000000000000014
              x: [ 0.000e+00 -0.000e+00 ...  0.000e+00  0.000e+00]
 mip_node_count: 1
 mip_dual_bound: 27.000000000000014
        mip_gap: 0.0

In [22]:
ilp.solve()
ilp.objective.value()

Welcome to the CBC MILP Solver 
Version: 2.10.3 
Build Date: Dec 15 2019 

command line - /home/tornikeo/micromamba/envs/pb/lib/python3.10/site-packages/pulp/solverdir/cbc/linux/64/cbc /tmp/710070db797f4cb1a5ee477859b9abbb-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/710070db797f4cb1a5ee477859b9abbb-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 437 COLUMNS
At line 1427 RHS
At line 1860 BOUNDS
At line 1995 ENDATA
Problem MODEL has 432 rows, 134 columns and 683 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 27 - 0.00 seconds
Cgl0003I 0 fixed, 0 tightened bounds, 6 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 0 tightened bounds, 6 strengthened rows, 0 substitutions
Cgl0004I processed model has 92 rows, 81 columns (81 integer (81 of which binary)) and 327 elements
Cutoff increment increased from 1e-05 to 0.4999
Cbc0038I Initial state - 0 integers

27.0

In [5]:
A.shape, c.shape

((460, 134), (134,))

In [6]:
# import numpy as np

# # Set random seed for reproducibility
# np.random.seed(42)

# # Problem size (small example)
# num_vars = 5  # Number of binary decision variables
# num_constraints = 3  # Number of constraints

# # Generate random cost vector c
# c = -np.random.randint(1, 10, size=num_vars)

# # Generate random constraint matrix A
# A = np.random.randint(0, 5, size=(num_constraints, num_vars))

# # Generate random upper bounds for constraints
# ub = np.random.randint(5, 15, size=num_constraints)

# # Lower bounds (all zero for inequalities)
# lb = np.zeros(num_constraints)

# # Define constraints
# constraints = LinearConstraint(A, lb, ub)

# # Define integer constraints (all variables are binary)
# integrality = np.ones(num_vars)

# # Solve using scipy.optimize.milp
# res = milp(c=c, constraints=constraints, integrality=integrality, bounds=(0, 1))

# # Display results
# res.x, res.fun

In [19]:
c

array([0.5, 0.5, 1. , 0. , 0. , 2. , 1. , 1. , 1. , 0. , 0. , 2. , 1. ,
       1. , 1. , 1. , 1. , 1. , 0. , 0. , 1.5, 0. , 0. , 1.5, 0. , 0. ,
       1.5, 0. , 0. , 1.5, 0. , 0. , 1.5, 0. , 0. , 1.5, 0.5, 0.5, 1. ,
       1. , 1.5, 1.5, 1. , 1.5, 1.5, 1.5, 1.5, 1.5, 2. , 1.5, 1. , 1.5,
       2. , 1.5, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. ])

In [ ]:
from itertools import product



def binary_milp(c, A, ub):
    num_vars = len(c)
    best_x = None
    best_obj = float('inf')

    # Generate all possible binary vectors
    for x in product([0, 1], repeat=num_vars):
        x = np.array(x)
        # Check feasibility: lb <= A @ x <= ub
        if np.all(A @ x <= ub):
            obj_value = c @ x  # Compute objective function

            # Update best solution if this one is better
            if obj_value < best_obj:
                best_obj = obj_value
                best_x = x.copy()
                print(best_obj)

    return best_x, best_obj

# Solve using our simple binary_milp function
binary_milp_solution = binary_milp(c, A, ub)
binary_milp_solution

KeyboardInterrupt: 

In [28]:
from itertools import product
from scipy.optimize import linprog

def greedy_feasible_solution(c, A, ub, lb):
    """Find a quick feasible solution to establish an upper bound."""
    num_vars = len(c)
    x = np.zeros(num_vars)  # Start with all zeros

    # Sort variables by cost-effectiveness (lowest c_i first, since we're minimizing)
    indices = np.argsort(c)

    # Try flipping variables to 1 while maintaining feasibility
    for i in indices:
        x[i] = 1
        if np.any(A @ x > ub) or np.any(A @ x < lb):
            x[i] = 0  # Revert if infeasible

    return x, c @ x  # Return feasible solution and its objective value


def lp_relaxation(c, A, ub, lb):
    """Solve LP relaxation to get fractional values."""
    res = linprog(c, A_ub=A, b_ub=ub, bounds=(0, 1), method='highs')
    return res.x if res.success else None, res.fun if res.success else float('inf')


def branch_and_bound(c, A, ub, lb, x_partial, depth, best_x, best_obj):
    """Recursive branch-and-bound solver."""
    num_vars = len(c)

    # Solve LP relaxation
    relaxed_x, relaxed_obj = lp_relaxation(c, A, ub, lb)

    # Prune if relaxation is worse than best known solution
    if relaxed_obj >= best_obj:
        return best_x, best_obj

    # Check if the relaxed solution is already integer
    if np.all(np.isclose(relaxed_x, np.round(relaxed_x))):
        return relaxed_x, relaxed_obj

    # Select the most fractional variable for branching
    fractional_vars = np.abs(relaxed_x - 0.5)
    branch_var = np.argmax(fractional_vars)

    # Try setting the variable to 0 and 1 recursively
    for val in [0, 1]:
        new_x_partial = x_partial.copy()
        new_x_partial[branch_var] = val

        # Check feasibility
        if np.all(A @ new_x_partial <= ub) and np.all(A @ new_x_partial >= lb):
            obj_value = c @ new_x_partial
            if obj_value < best_obj:
                best_x, best_obj = new_x_partial.copy(), obj_value

            # Recursively branch
            best_x, best_obj = branch_and_bound(c, A, ub, lb, new_x_partial, depth + 1, best_x, best_obj)

    return best_x, best_obj


def binary_milp(c, A, ub, lb):
    """Main function to solve binary integer programming using branch-and-bound."""
    num_vars = len(c)

    # Get initial feasible solution
    best_x, best_obj = greedy_feasible_solution(c, A, ub, lb)

    # Start branch-and-bound
    x_partial = np.full(num_vars, -1)  # -1 means unassigned
    best_x, best_obj = branch_and_bound(c, A, ub, lb, x_partial, 0, best_x, best_obj)

    return best_x, best_obj

# Solve using the improved binary_milp function
binary_milp_solution = binary_milp(-c, A, ub, np.full_like(ub, -np.inf))
binary_milp_solution

(array([-0., -0.,  1.,  0.,  0.,  1., -0., -0.,  1.,  0.,  0.,  1., -0.,
         0.,  1., -0., -0.,  1.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,
         1.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  1., -0.,  0.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  0.,  0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,  0.,  0.,
         0., -0., -0., -0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0., -0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.]),
 -40.0)

In [17]:
np.sort(c)[::-1]

array([2. , 2. , 2. , 2. , 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5,
       1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1. , 1. , 1. , 1. , 1. , 1. ,
       1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 0.5, 0.5, 0.5, 0.5, 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. ])